/**
 * Allianz Payment Tracker - Full Student Dataset (156 Students)
 */
window.ALLIANZ_STUDENTS_DATA = [
  { "id": "1", "curso": "5R", "name": "Almécija Sánchez Clementina del Valle", "paid_status": false },
  { "id": "2", "curso": "5P", "name": "Ancares Rojas Augusto Ignacio", "paid_status": false },
  { "id": "3", "curso": "5R", "name": "Artigas Aravena Juan José", "paid_status": false },
  { "id": "4", "curso": "5R", "name": "Balbontin Novoa Santiago", "paid_status": false },
  { "id": "5", "curso": "5R", "name": "Beriestain Escoda Augusto Simón", "paid_status": false },
  { "id": "6", "curso": "5P", "name": "Carvajal Gutiérrez Amanda Sofia", "paid_status": false },
  { "id": "7", "curso": "5R", "name": "Carvajal Gutiérrez Vicente Andrés", "paid_status": false },
  { "id": "8", "curso": "5P", "name": "Contreras Yañez Matias Javier", "paid_status": false },
  { "id": "9", "curso": "5P", "name": "Dinamarca Araya Rosario Isabel", "paid_status": false },
  { "id": "10", "curso": "5P", "name": "Galleguillos Leiva Elena Paz", "paid_status": false },
  { "id": "11", "curso": "5P", "name": "Guzmán Candia Ricardo Antonio", "paid_status": false },
  { "id": "12", "curso": "5R", "name": "Isaacs Izaurieta Facundo Tomas", "paid_status": false },
  { "id": "13", "curso": "5P", "name": "Moguilevsky Hovsepian Eva", "paid_status": false },
  { "id": "14", "curso": "5P", "name": "Muñoz Mora Franco Esteban", "paid_status": false },
  { "id": "15", "curso": "5P", "name": "Pastén Navas Florencia", "paid_status": false },
  { "id": "16", "curso": "5P", "name": "Sambuceti Ghisolfo Antonia", "paid_status": false },
  { "id": "17", "curso": "6L", "name": "Atán Mendoza Ignacia Agustina", "paid_status": false },
  { "id": "18", "curso": "6V", "name": "Belisario Gauthier Alanna Sofia", "paid_status": false },
  { "id": "19", "curso": "6V", "name": "Bustamante Brierley Santiago", "paid_status": false },
  { "id": "20", "curso": "6V", "name": "Castro Napolitano Diego Agustin", "paid_status": false },
  { "id": "21", "curso": "6V", "name": "Cogollor Olivares Tomas Ignacio", "paid_status": false },
  { "id": "22", "curso": "6V", "name": "Diaz Burgos Maite Sofia", "paid_status": false },
  { "id": "23", "curso": "6L", "name": "Dominguez Herreros Anton Jose", "paid_status": false },
  { "id": "24", "curso": "6V", "name": "Fuentealba Aguilera Alfonso Julian", "paid_status": false },
  { "id": "25", "curso": "6V", "name": "Gallardo de la Paz Emma Antonella", "paid_status": false },
  { "id": "26", "curso": "6L", "name": "Guler Mackenna Kenneth", "paid_status": false },
  { "id": "27", "curso": "6L", "name": "Guerra Alvarez Julieta Isidora Del Carmen", "paid_status": false },
  { "id": "28", "curso": "6V", "name": "Jousse Páez Micaela", "paid_status": false },
  { "id": "29", "curso": "6L", "name": "Jousse Páez Thiago", "paid_status": false },
  { "id": "30", "curso": "6L", "name": "Lee Elsa", "paid_status": false },
  { "id": "31", "curso": "6V", "name": "Lopez Calderon Beatriz Antonia", "paid_status": false },
  { "id": "32", "curso": "6L", "name": "Modermot Padilla Stella", "paid_status": false },
  { "id": "33", "curso": "6L", "name": "Olate Hadad Bruno", "paid_status": false },
  { "id": "34", "curso": "6V", "name": "Requena Hernández Lorenza", "paid_status": false },
  { "id": "35", "curso": "6L", "name": "Silva Trujillo Ignacia Catalina", "paid_status": false },
  { "id": "36", "curso": "6V", "name": "Tagle Urzúa Lean", "paid_status": false },
  { "id": "37", "curso": "6V", "name": "Vieira Coronel Gulliana", "paid_status": false },
  { "id": "38", "curso": "6L", "name": "Zapata Murcia Maite Sofia", "paid_status": false },
  { "id": "39", "curso": "7J", "name": "Alburquenque Santibáñez Agustín Ignacio", "paid_status": false },
  { "id": "40", "curso": "7M", "name": "Allel Figueroa Lucas", "paid_status": false },
  { "id": "41", "curso": "7J", "name": "Ancares Rojas José Alfredo", "paid_status": false },
  { "id": "42", "curso": "7J", "name": "Arriagada Bermudez Julia", "paid_status": false },
  { "id": "43", "curso": "7J", "name": "Boñon Negron Camila Valentina", "paid_status": false },
  { "id": "44", "curso": "7M", "name": "Casanueva Pinto Benjamin", "paid_status": false },
  { "id": "45", "curso": "7M", "name": "Castillo Lazcano Josefa", "paid_status": false },
  { "id": "46", "curso": "7J", "name": "Correa Godoy Elisa Ignacia", "paid_status": false },
  { "id": "47", "curso": "7M", "name": "Escalona Canales Facundo Ignacio", "paid_status": false },
  { "id": "48", "curso": "7J", "name": "Landesman Montabone Tomás", "paid_status": false },
  { "id": "49", "curso": "7M", "name": "Mol Martins Maria Eduarda", "paid_status": false },
  { "id": "50", "curso": "7J", "name": "Mora Manriquez Claudia Antonia", "paid_status": false },
  { "id": "51", "curso": "7J", "name": "Parragué Govorcin Joaquin", "paid_status": false },
  { "id": "52", "curso": "7M", "name": "Retamal Alvarez de Araya José Tomás", "paid_status": false },
  { "id": "53", "curso": "7J", "name": "Ricart Osorio Lucas", "paid_status": false },
  { "id": "54", "curso": "7M", "name": "Salgado Valech Nicolas", "paid_status": false },
  { "id": "55", "curso": "7M", "name": "Salinas Venegas Fernando Andres", "paid_status": false },
  { "id": "56", "curso": "7M", "name": "Sepulveda Rivas Catalina Belen", "paid_status": false },
  { "id": "57", "curso": "7J", "name": "Soto Dumont Agustina", "paid_status": false },
  { "id": "58", "curso": "7M", "name": "Staforelli Araya Elisa Carolina", "paid_status": false },
  { "id": "59", "curso": "7M", "name": "Uriarte Berrios Catalina Ignacia", "paid_status": false },
  { "id": "60", "curso": "7J", "name": "Zerbi Montenegro Ema", "paid_status": false },
  { "id": "61", "curso": "7J", "name": "Zurob Lanzarini Olivia", "paid_status": false },
  { "id": "62", "curso": "8E", "name": "Almécija Sánchez Cristóbal Jesús", "paid_status": false },
  { "id": "63", "curso": "8M", "name": "Baeza Cárdenas Mateo José", "paid_status": false },
  { "id": "64", "curso": "8E", "name": "Baeza Cárdenas Rafaela Aurora", "paid_status": false },
  { "id": "65", "curso": "8M", "name": "Beriestain Escoda Julia Elena", "paid_status": false },
  { "id": "66", "curso": "8M", "name": "Bolognesi Aguado Bruno", "paid_status": false },
  { "id": "67", "curso": "8M", "name": "Cerda Arias Martina", "paid_status": false },
  { "id": "68", "curso": "8M", "name": "Cogollor Olivares Valentina Ignacia", "paid_status": false },
  { "id": "69", "curso": "8E", "name": "Contreras Yañez Tomás José", "paid_status": false },
  { "id": "70", "curso": "8M", "name": "Cozzi Ortiz Ema", "paid_status": false },
  { "id": "71", "curso": "8E", "name": "Dinamarca Araya José Pedro", "paid_status": false },
  { "id": "72", "curso": "8E", "name": "Ferreira Cardemil Zoe", "paid_status": false },
  { "id": "73", "curso": "8E", "name": "Fuenzalida Montecinos Isidora Constanza", "paid_status": false },
  { "id": "74", "curso": "8M", "name": "Grez Pérez Gaspar Ignacio", "paid_status": false },
  { "id": "75", "curso": "8M", "name": "Guler Mackenna Isabel", "paid_status": false },
  { "id": "76", "curso": "8E", "name": "Jang Jihwan", "paid_status": false },
  { "id": "77", "curso": "8E", "name": "Jousse Páez Zoe", "paid_status": false },
  { "id": "78", "curso": "8E", "name": "Lucero Carreño Benjamin Andrés", "paid_status": false },
  { "id": "79", "curso": "8E", "name": "Pastén Navas Magdalena Antonia", "paid_status": false },
  { "id": "80", "curso": "8M", "name": "Perez Ruz Laura Carolina", "paid_status": false },
  { "id": "81", "curso": "8M", "name": "Torres Zhang Isidora Liyi", "paid_status": false },
  { "id": "82", "curso": "8M", "name": "Vergara Marin Matias Ricardo", "paid_status": false },
  { "id": "83", "curso": "9P", "name": "Allel Figueroa Emma", "paid_status": false },
  { "id": "84", "curso": "9D", "name": "Aparicio Riera Nicolás", "paid_status": false },
  { "id": "85", "curso": "9P", "name": "Artigas Aravena Pedro Andrés", "paid_status": false },
  { "id": "86", "curso": "9D", "name": "Cerda Guerrero Jorge Alejandro", "paid_status": false },
  { "id": "87", "curso": "9D", "name": "Concha Pastene Camilo Agustin", "paid_status": false },
  { "id": "88", "curso": "9P", "name": "Delgado Noches Felipe Antonio", "paid_status": false },
  { "id": "89", "curso": "9D", "name": "Landesman Montabone Emma", "paid_status": false },
  { "id": "90", "curso": "9D", "name": "Lee Ithiel", "paid_status": false },
  { "id": "91", "curso": "9D", "name": "Manns Sepúlveda Rafael", "paid_status": false },
  { "id": "92", "curso": "9P", "name": "Molina Álvarez Alicia Fernanda", "paid_status": false },
  { "id": "93", "curso": "9D", "name": "Muñoz Roa Emilia Alejandra", "paid_status": false },
  { "id": "94", "curso": "9D", "name": "Nervi Medina Bianca Simona", "paid_status": false },
  { "id": "95", "curso": "9P", "name": "Opazo Noguez Josefina Ignacial", "paid_status": false },
  { "id": "96", "curso": "9D", "name": "Pardo Jiménez Julia", "paid_status": false },
  { "id": "97", "curso": "9D", "name": "Parraqué Govorcin Samuel", "paid_status": false },
  { "id": "98", "curso": "9P", "name": "Parragué Moses Alma", "paid_status": false },
  { "id": "99", "curso": "9D", "name": "Rechter Aguilera Raimundo León", "paid_status": false },
  { "id": "100", "curso": "9P", "name": "Retamal Nuñez Constanza", "paid_status": false },
  { "id": "101", "curso": "9P", "name": "Salinas Venegas Sofia Francisca", "paid_status": false },
  { "id": "102", "curso": "9D", "name": "Sambuceti Ghisolfo Domenica", "paid_status": false },
  { "id": "103", "curso": "9P", "name": "Schrader Sánchez Rafaella", "paid_status": false },
  { "id": "104", "curso": "9D", "name": "Seguel Pucciarelli Josefa Amalia", "paid_status": false },
  { "id": "105", "curso": "9P", "name": "Senn Flores Gabriel Alfredo", "paid_status": false },
  { "id": "106", "curso": "9P", "name": "Torres Carmona Zoé", "paid_status": false },
  { "id": "107", "curso": "10B", "name": "Aldunate Barrionuevo José Felipe", "paid_status": false },
  { "id": "108", "curso": "10B", "name": "Boñon Negrón Sofia Abigail", "paid_status": false },
  { "id": "109", "curso": "10P", "name": "Cabrera Ronda Rafael Ignacio", "paid_status": false },
  { "id": "110", "curso": "10P", "name": "Cartes Quintana Matilde Amelia", "paid_status": false },
  { "id": "111", "curso": "10P", "name": "Contreras Yañez Sebastián León", "paid_status": false },
  { "id": "112", "curso": "10P", "name": "Correa Gonzalez Dominga Maria", "paid_status": false },
  { "id": "113", "curso": "10P", "name": "Curotto Alvarez Franco", "paid_status": false },
  { "id": "114", "curso": "10P", "name": "Diaz Novoa Benjamin", "paid_status": false },
  { "id": "115", "curso": "10P", "name": "Fuenzalida Montecinos Nicolás Ignacio", "paid_status": false },
  { "id": "116", "curso": "10P", "name": "Grez Pérez Gaspar José Miquel", "paid_status": false },
  { "id": "117", "curso": "10B", "name": "Grune Toso Trinidad", "paid_status": false },
  { "id": "118", "curso": "10P", "name": "Guler Mackenna Florencia", "paid_status": false },
  { "id": "119", "curso": "10B", "name": "Ljubetic Soto Tonka Maria", "paid_status": false },
  { "id": "120", "curso": "10P", "name": "Nervi Martinez Amanda Jesús", "paid_status": false },
  { "id": "121", "curso": "10P", "name": "Trujillo Bascur José Tomás", "paid_status": false },
  { "id": "122", "curso": "10P", "name": "Vega Salamino Celeste Amanda", "paid_status": false },
  { "id": "123", "curso": "11R", "name": "Acuña Díaz Francisca", "paid_status": false },
  { "id": "124", "curso": "11AM", "name": "Alarcón Varela Gonzalo", "paid_status": false },
  { "id": "125", "curso": "11AM", "name": "Amigo Marin Agustin Antonio", "paid_status": false },
  { "id": "126", "curso": "11AM", "name": "Aparicio Riera María Jesús", "paid_status": false },
  { "id": "127", "curso": "11AM", "name": "Castro Napolitano Tomás Ignacio", "paid_status": false },
  { "id": "128", "curso": "11R", "name": "Chueco López Alonso", "paid_status": false },
  { "id": "129", "curso": "11AM", "name": "Concha Pastene Martin Andrés", "paid_status": false },
  { "id": "130", "curso": "11AM", "name": "Fuentealba Aguilera Agustina Antonia", "paid_status": false },
  { "id": "131", "curso": "11AM", "name": "Kaiser Valdivieso Agustin Ignacio", "paid_status": false },
  { "id": "132", "curso": "11R", "name": "Mora Manriquez Montserrat Aracell", "paid_status": false },
  { "id": "133", "curso": "11R", "name": "Rechter Aguilera Sofia Macarena", "paid_status": false },
  { "id": "134", "curso": "11R", "name": "Retamal Núñez Vicente Javier", "paid_status": false },
  { "id": "135", "curso": "11R", "name": "Rojas Farias Florencia Belen", "paid_status": false },
  { "id": "136", "curso": "11R", "name": "Soto Sandoval Gabriela", "paid_status": false },
  { "id": "137", "curso": "11AM", "name": "Uriarte Berrios Benjamin Ignacio", "paid_status": false },
  { "id": "138", "curso": "11AM", "name": "Venegas Muñoz Gabriel", "paid_status": false },
  { "id": "139", "curso": "12E", "name": "Bolognesi Aguado Emilia", "paid_status": false },
  { "id": "140", "curso": "12D", "name": "Bolognesi Raineri Matteo", "paid_status": false },
  { "id": "141", "curso": "12D", "name": "Boñon Negrón Mauricio Santiago", "paid_status": false },
  { "id": "142", "curso": "12E", "name": "Bunster Bunster Josefina", "paid_status": false },
  { "id": "143", "curso": "12D", "name": "Curotto Álvarez Rafaella", "paid_status": false },
  { "id": "144", "curso": "12D", "name": "Diaz Betancourt José Tomás", "paid_status": false },
  { "id": "145", "curso": "12E", "name": "Lee Joung Dong Won", "paid_status": false },
  { "id": "146", "curso": "12D", "name": "Mendizabal Martorell Melina", "paid_status": false },
  { "id": "147", "curso": "12D", "name": "Nervi Medina Rafaella Luciana", "paid_status": false },
  { "id": "148", "curso": "12E", "name": "Opazo Noguez Matías", "paid_status": false },
  { "id": "149", "curso": "12E", "name": "Park You Fabián Sejun", "paid_status": false },
  { "id": "150", "curso": "12E", "name": "Parragué Moses Nicolás Eliel", "paid_status": false },
  { "id": "151", "curso": "12E", "name": "Pérez Ruz Gabriela Constanza", "paid_status": false },
  { "id": "152", "curso": "12E", "name": "Puentes León Emily Belén", "paid_status": false },
  { "id": "153", "curso": "12D", "name": "Rojas Farias Maximiliano Andres Leon Claudio", "paid_status": false },
  { "id": "154", "curso": "12E", "name": "Silva Browne Isidora", "paid_status": false },
  { "id": "155", "curso": "12E", "name": "Vergara Rodriguez Martin Felipe", "paid_status": false },
  { "id": "156", "curso": "12D", "name": "Vergara Rodriguez Tomás Eugenio", "paid_status": false }
];
